# Generated by Django 3.2.13 on 2022-05-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_cointype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointype',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchasecoins',
            name='coin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_coins', to='coins.cointype'),
        ),
    ]
