# Generated by Django 3.2.13 on 2022-05-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_alter_coins_coin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='id',
        ),
        migrations.AlterField(
            model_name='coins',
            name='coin_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='coins.cointype'),
        ),
    ]
