# Generated by Django 3.2.13 on 2022-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
